export type AppErrorCode =
  | "STAKE_INVALID_URL"
  | "STAKE_EVENT_NOT_FOUND"
  | "STAKE_PAGE_TIMEOUT"
  | "STAKE_BLOCKED_OR_CHALLENGED"
  | "STAKE_NO_MARKETS_FOUND"
  | "STAKE_SCHEMA_CHANGED"
  | "STAKE_IMPORT_ALREADY_FROZEN"
  | "STAKE_API_URL_NOT_RESOLVED"
  | "STAKE_API_HOST_NOT_ALLOWED"
  | "STAKE_API_EVENT_ID_MISMATCH"
  | "STAKE_API_HTTP_ERROR"
  | "STAKE_API_INVALID_CONTENT_TYPE"
  | "STAKE_API_INVALID_PAYLOAD"
  | "STAKE_API_NO_ODDS"
  | "STAKE_API_TIMEOUT"
  | "STAKE_API_RESPONSE_TOO_LARGE"
  | "SPORTS_PROVIDER_UNAUTHORIZED"
  | "SPORTS_PROVIDER_RATE_LIMITED"
  | "SPORTS_FIXTURE_NOT_FOUND"
  | "SPORTS_FIXTURE_MISMATCH"
  | "SPORTS_FIXTURE_NOT_FINISHED"
  | "SPORTS_FIXTURE_AMBIGUOUS"
  | "SPORTS_PROVIDER_TIMEOUT"
  | "SPORTS_PROVIDER_INVALID_RESPONSE"
  | "VALIDATION_FAILED";

export class AppError extends Error {
  readonly code: AppErrorCode;
  readonly status: number;

  constructor(code: AppErrorCode, message: string, status = 400) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.status = status;
  }
}
